apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: note-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Chenarrr/k8s-Infra-.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: notes-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


      