apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: notes-app
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: notes-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 80
