apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: notes-app
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: notes-app
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
